create table study
(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(255),
    date varchar(255),

    url varchar(255),

    fileOriginName varchar(255),
    fileSaveName varchar(255),
    fileSavePath varchar(255),

    primary key (id)

);